# -*- coding: utf-8 -*-
"""advanced_algae_reactor_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16-d1trIuk6i7aUqkbq-ZnuHPdK1x7TLC
"""

import numpy as np
from scipy.integrate import odeint
import matplotlib.pyplot as plt

# ==============================
# PARAMETERS
# ==============================

# Growth
mu_max = 0.09
Ks = 0.03
Ki = 50             # Light saturation constant

# Yield
Yx_co2 = 1.8

# Reactor
kLa = 0.6
C_star = 0.04

# Light
I0 = 200            # surface light (µmol/m²/s)
k_light = 0.15      # light attenuation coefficient
H = 0.5             # reactor depth (m)

# Initial conditions
X0 = 0.1
C0 = 0.02
y0 = [X0, C0]

t = np.linspace(0, 120, 600)

# ==============================
# LIGHT MODEL
# ==============================

def avg_light_intensity(X):
    if X <= 1e-6:
        return I0
    return (I0 / (k_light * X * H)) * (1 - np.exp(-k_light * X * H))

# ==============================
# MODEL
# ==============================

def reactor_model(y, t):
    X, C = y

    I_avg = avg_light_intensity(X)

    # Coupled growth rate
    mu = mu_max * (C / (Ks + C)) * (I_avg / (Ki + I_avg))

    dXdt = mu * X

    CO2_consumption = (1 / Yx_co2) * dXdt
    CO2_transfer = kLa * (C_star - C)

    dCdt = CO2_transfer - CO2_consumption

    return [dXdt, dCdt]

# ==============================
# SIMULATION
# ==============================

solution = odeint(reactor_model, y0, t)
X = solution[:, 0]
C = solution[:, 1]

# ==============================
# OPTIMIZATION (Light Sweep)
# ==============================

light_range = np.linspace(50, 400, 20)
final_biomass = []

for light in light_range:
    I0 = light  # vary light input

    sol = odeint(reactor_model, y0, t)
    final_biomass.append(sol[-1, 0])

# ==============================
# INDUSTRIAL SCALING
# ==============================

reactor_volumes = [10, 100, 1000]  # Liters

scaling_results = {}

for V in reactor_volumes:
    scale_factor = V / 10
    scaled_kLa = kLa / (scale_factor**0.2)  # empirical scaling

    def scaled_model(y, t):
        X, C = y

        I_avg = avg_light_intensity(X)
        mu = mu_max * (C / (Ks + C)) * (I_avg / (Ki + I_avg))

        dXdt = mu * X
        CO2_consumption = (1 / Yx_co2) * dXdt
        CO2_transfer = scaled_kLa * (C_star - C)

        dCdt = CO2_transfer - CO2_consumption

        return [dXdt, dCdt]

    sol = odeint(scaled_model, y0, t)
    scaling_results[V] = sol[:, 0]

# ==============================
# PLOTTING
# ==============================

# Growth
plt.figure()
plt.plot(t, X, label="Biomass")
plt.xlabel("Time (hr)")
plt.ylabel("Biomass (g/L)")
plt.title("Growth with Light Limitation")
plt.legend()

# Optimization
plt.figure()
plt.plot(light_range, final_biomass)
plt.xlabel("Light Intensity")
plt.ylabel("Final Biomass")
plt.title("Optimization of Light Input")

# Scaling
plt.figure()
for V in reactor_volumes:
    plt.plot(t, scaling_results[V], label=f"{V} L Reactor")

plt.xlabel("Time (hr)")
plt.ylabel("Biomass")
plt.title("Industrial Scale-Up Effect")
plt.legend()

plt.show()