# -*- coding: utf-8 -*-
"""ai_optimized_algae_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lL1is5bfS6UgRRb4PS4mR3etrVxWptcq
"""

import numpy as np
from scipy.integrate import odeint
import matplotlib.pyplot as plt
import random

# ==============================
# GLOBAL PARAMETERS
# ==============================

mu_max = 0.09
Ks = 0.03
Ki = 50
Yx_co2 = 1.8

# Economic parameters
electricity_cost = 0.1     # $/kWh
carbon_price = 50          # $/ton CO2
reactor_cost_per_L = 2     # $/L

# Time
t = np.linspace(0, 120, 500)

# Initial conditions
X0 = 0.1
C0 = 0.02
y0 = [X0, C0]

# ==============================
# MODEL FUNCTION
# ==============================

def simulate(params):
    I0, kLa, H, k_light = params

    def avg_light(X):
        if X < 1e-6:
            return I0
        return (I0 / (k_light * X * H)) * (1 - np.exp(-k_light * X * H))

    def model(y, t):
        X, C = y

        I_avg = avg_light(X)
        mu = mu_max * (C / (Ks + C)) * (I_avg / (Ki + I_avg))

        dXdt = mu * X

        CO2_consumption = (1 / Yx_co2) * dXdt
        CO2_transfer = kLa * (0.04 - C)

        dCdt = CO2_transfer - CO2_consumption

        return [dXdt, dCdt]

    sol = odeint(model, y0, t)

    X_final = sol[-1, 0]
    C_final = sol[-1, 1]

    CO2_captured = (C0 - C_final)  # g/L

    return X_final, CO2_captured


# ==============================
# COST MODEL
# ==============================

def cost_model(params, volume=1000):
    I0, kLa, H, k_light = params

    energy_use = I0 * 0.01  # simplified scaling
    energy_cost = energy_use * electricity_cost

    capex = volume * reactor_cost_per_L

    return energy_cost + capex / 1000  # amortized


# ==============================
# CARBON REVENUE
# ==============================

def carbon_revenue(CO2_captured, volume=1000):
    # Convert g/L → tons
    tons = CO2_captured * volume / 1e6
    return tons * carbon_price


# ==============================
# FITNESS FUNCTION
# ==============================

def fitness(params):
    X, CO2 = simulate(params)

    revenue = carbon_revenue(CO2)
    cost = cost_model(params)

    profit = revenue - cost

    return profit


# ==============================
# AI OPTIMIZATION (GENETIC STYLE)
# ==============================

def random_params():
    return [
        random.uniform(50, 400),   # I0
        random.uniform(0.2, 1.0),  # kLa
        random.uniform(0.2, 1.0),  # H
        random.uniform(0.05, 0.3)  # k_light
    ]

population = [random_params() for _ in range(20)]

generations = 15

best_history = []

for gen in range(generations):
    scores = [(fitness(p), p) for p in population]
    scores.sort(reverse=True, key=lambda x: x[0])

    best_history.append(scores[0][0])

    # Select top 50%
    survivors = [p for _, p in scores[:10]]

    # Reproduce
    new_population = survivors.copy()

    while len(new_population) < 20:
        parent = random.choice(survivors)
        child = [val * random.uniform(0.9, 1.1) for val in parent]
        new_population.append(child)

    population = new_population

best_params = scores[0][1]
best_profit = scores[0][0]

print("Best Parameters:")
print(f"I0={best_params[0]:.2f}, kLa={best_params[1]:.2f}, H={best_params[2]:.2f}, k_light={best_params[3]:.2f}")
print("Max Profit:", best_profit)

# ==============================
# VISUALIZATION
# ==============================

plt.figure()
plt.plot(best_history)
plt.xlabel("Generation")
plt.ylabel("Profit")
plt.title("AI Optimization Progress")

plt.show()