# -*- coding: utf-8 -*-
"""integrated_algae_reactor_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zw-NDjx-wL66uAaIYZRinfSNFevF_bA1
"""

import numpy as np
from scipy.integrate import odeint
import matplotlib.pyplot as plt

# ==============================
# PARAMETERS
# ==============================

# Growth parameters
mu_max = 0.08        # 1/hr
Ks = 0.03            # g/L (half-saturation constant)

# Yield
Yx_co2 = 1.8         # g biomass / g CO2

# Reactor parameters
kLa = 0.5            # 1/hr (mass transfer coefficient)
C_star = 0.04        # g/L (saturation CO2 concentration)

# Initial conditions
X0 = 0.1             # biomass (g/L)
C0 = 0.02            # CO2 concentration (g/L)

y0 = [X0, C0]

# Time span
t = np.linspace(0, 100, 500)

# ==============================
# MODEL EQUATIONS
# ==============================

def reactor_model(y, t):
    X, C = y

    # Growth rate (Monod kinetics)
    mu = mu_max * (C / (Ks + C))

    # Biomass growth
    dXdt = mu * X

    # CO2 consumption by algae
    CO2_consumption = (1 / Yx_co2) * dXdt

    # Gas-liquid transfer
    CO2_transfer = kLa * (C_star - C)

    # CO2 balance
    dCdt = CO2_transfer - CO2_consumption

    return [dXdt, dCdt]

# ==============================
# SOLVE ODE
# ==============================

solution = odeint(reactor_model, y0, t)
X = solution[:, 0]
C = solution[:, 1]

# ==============================
# PLOTTING
# ==============================

plt.figure()
plt.plot(t, X, label="Biomass (g/L)")
plt.xlabel("Time (hr)")
plt.ylabel("Biomass Concentration")
plt.legend()
plt.title("Algae Growth in Photobioreactor")

plt.figure()
plt.plot(t, C, label="CO2 (g/L)")
plt.xlabel("Time (hr)")
plt.ylabel("CO2 Concentration")
plt.legend()
plt.title("CO2 Dynamics in Reactor")

plt.figure()
plt.plot(t, X, label="Biomass")
plt.plot(t, C, label="CO2")
plt.xlabel("Time (hr)")
plt.ylabel("Concentration")
plt.legend()
plt.title("Coupled System Behavior")

plt.show()